version: '3'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: service-desk-frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NEXT_PUBLIC_BACKEND_URL=http://213.210.36.2:8000
      - NEXT_PUBLIC_WS_URL=ws://213.210.36.2:8000
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    env_file:
      - .env

  backend:
    build: ./backend
    container_name: service-desk-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=development
      - PORT=8000
      - HOST=0.0.0.0
      - WORKERS=1
      - RELOAD=true
      - ALLOWED_ORIGINS=http://213.210.36.2:3000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - chromadb
    networks:
      - app-network
    restart: unless-stopped
    env_file:
      - .env
  
  chromadb:
    image: chromadb/chroma
    container_name: service-desk-chromadb
    ports:
      - "8001:8000"
    volumes:
      - chromadb_data:/chroma/data
    networks:
      - app-network
    restart: unless-stopped
    env_file:
      - .env
  
networks:
  app-network:
    driver: bridge

volumes:
  chromadb_data:
