version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: service-desk-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: service-desk-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=development
    depends_on:
      - chromadb
    networks:
      - app-network
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma
    container_name: service-desk-chromadb
    ports:
      - "8001:8000"
    volumes:
      - chromadb_data:/chroma/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  chromadb_data:
